Multiple lines on text field
kyechan99/capsule-render pull request #17
Opened 2023-02-17 21:08 UTC by kauer3

![header](https://capsule-render-kauer3.vercel.app/api?height=240&text=Capsule-nl-Render&fontAlign=25&fontAlign=39&fontAlignY=23&fontAlignY=54)

---

As suggested at #15, this PR implements the possibility to add line breaks to the text field. To use this feature, the user should insert the characters `-nl-`, and the following text will be displayed in a new line. 

```
![header](https://capsule-render-kauer3.vercel.app/api?type=rect&height=220&text=first%20line-nl-Second%20Line-nl-third%20line
```

![header](https://capsule-render-kauer3.vercel.app/api?type=rect&height=220&text=first%20line-nl-Second%20Line-nl-third%20line)

The default value for `fontAlignY`, which is still 50 when there's only one line, is calculated when there are multiple lines in order to centralize the text vertically. However, it's also possible to set the `fontAlignY` value manually and individually for each line. To do so, the user should set multiples `&fontAlignY=` parameters, where the first one will correspond to the first line, the second to the second line, and so on. If there are more lines than `&fontAlignY=` parameters, then the remaining lines will have their vertical position calculated automatically. For example, if there are 4 lines, but only 2 `&fontAlignY=` parameters, then the first and second lines will have their vertical position set by the first and second parameter, the third line will be positioned automatically after the second line, and the fourth after the third.

Example: 
```
![header](https://capsule-render-kauer3.vercel.app/api?type=rect&height=350&text=first%20line-nl-Second%20Line-nl-third%20line-nl-fourth&fontAlignY=11&fontAlignY=48)
```

![header](https://capsule-render-kauer3.vercel.app/api?type=rect&height=350&text=first%20line-nl-Second%20Line-nl-third%20line-nl-fourth&fontAlignY=11&fontAlignY=48)

Likewise, it's also possible to use multiple `&fontAlign` parameters to set the horizontal position of each line individually:

```
![header](https://capsule-render-kauer3.vercel.app/api?type=rect&height=300&text=Line%20ONE-nl-Line%202-nl-Line%20Three&fontAlign=75&fontAlign=17)
```

![header](https://capsule-render-kauer3.vercel.app/api?type=rect&height=300&text=Line%20ONE-nl-Line%202-nl-Line%20Three&fontAlign=75&fontAlign=17)

When there are too many lines, setting parameters like `height`, `fontSize` or `fontAlignY`could be needed to fit all lines inside the image.

2023-02-18 06:58 UTC, kyechan99 requested changes
👍 

Could you change the code of this [index.js#L71](https://github.com/kyechan99/capsule-render/pull/17/files?diff=split&w=0#diff-0cd6077e2a9b32718203a28a9a3c363aef0be6a1516e863b91fb0bc842133933L71) to the following?


#### Current
```
? model.textBg(fontColor, fontAlign, fontAlignY, fontSize, text)
```
#### Change to
```
? model.textBg(fontColor, fontAlign || 50, fontAlignY || 50, fontSize, text)
```

2023-02-18 07:03 UTC, kyechan99 commented
Awesome !! 👍 
It's a really nice feature to be able to adjust the position per line.

However, there is a bug in using `textBg` in changing the default value of `fontAlign` and `fontAlignY` to 0.
So.. trying to replace one line of code in the code review above by modifying it.

Also, is it possible to modify the README for the added function?
Everything is perfect :)

2023-02-21 07:10 UTC, kauer3 commented
I replaced the line as requested. I will also update the README and check for more bugs, but probably not in the next days, having a busy week :)

2023-02-21 08:08 UTC, kyechan99 reviewed
thx 👍

2023-02-21 08:08 UTC, merged